#include <vector>
#include <string>

using namespace std;

class Bignum {

public:
	//Constructors
	Bignum();
	Bignum(string&);

	//Getters
	string getnum();
	string getexpnum();

	//operator overloads for addition, subtract, and multiplication
	Bignum operator+(Bignum&); 
	Bignum operator-(Bignum&);
	Bignum operator*(Bignum&);

private:
	string number;
	int decimal_place;
	bool isNegative = false;

	static const int DIGITS_PER_LL;
	static const int SIG_FIGS;
	static const int MULTIPLICATION_DIGITS;

    // Private constructor used for quickly creating a Bignum of only 0s
    // Bignums generated by this constructor are used to store multiplication results
    Bignum(int, int);

    // The following two methods are helper functions that assist with
    // Decimal aligning two Bignums, to prepare them for addition or subtraction
	void add_zeros_left(int);
	void add_zeros_right(int);

	void decimal_align(Bignum&);
	void compress();

	bool operator<(Bignum&);
	bool operator>(Bignum&);
};
